### ISSUE TITLE
the app won't start, using ubuntu 14.04 

### ISSUE THREAD

**Issue by mehdi-alouane** [Aluxian/Messenger-for-Desktop#453] opened 2016-06-21 20:54 UTC
![screenshot from 2016-06-21 20 53 28](https://cloud.githubusercontent.com/assets/4208162/16245853/4657cf1c-37f2-11e6-9a85-393d35195cf0.png)

**Comment by fabpin** [comment] 2016-06-22 00:02
the same problem, you have problem with the SSL,suppose  than caduceus
![captura de pantalla de 2016-06-21 19 00 29](https://cloud.githubusercontent.com/assets/8019419/16250399/a85e5de4-37e2-11e6-9bc1-27897a702010.png)

**Comment by Shdwnova** [comment] 2016-06-22 14:50
Same Issue on Ubuntu 16.04...

[4015:0622/104625:ERROR:browser_main_loop.cc(170)] Running without the SUID sandbox! See https://code.google.com/p/chromium/wiki/LinuxSUIDSandboxDevelopment for more information on developing with the sandbox on.
ATTENTION: default value of option force_s3tc_enable overridden by environment.
[4037:0622/104626:ERROR:sandbox_linux.cc(325)] InitializeSandbox() called with multiple threads in process gpu-process
[4015:0622/104626:WARNING:nss_ssl_util.cc(374)] Unknown SSL error -12218 (SSL_ERROR_ENCRYPTION_FAILURE) mapped to net::ERR_SSL_PROTOCOL_ERROR
[4047:0622/104648:ERROR:channel.cc(305)] RawChannel read error (connection broken)

**Comment by mcdansg** [comment] 2016-06-22 21:11
Same issue and error message as Shdwnova on Linux Mint 17.3 Mate edition.  Started two days ago for me.

**Comment by rvteja92** [comment] 2016-06-23 03:37
Same issue for me too, on Ubuntu 14.04
![messenger](https://cloud.githubusercontent.com/assets/9823712/16291201/f062169a-3921-11e6-9d68-6f0333f4f1d8.png)

**Comment by AllanDaemon** [comment] 2016-06-23 03:44
Same issue here. Using Debian Unstable (SID) 64 bits.

**Comment by podarok** [comment] 2016-06-23 07:13
Ubuntu 16.04 confirmed

**Comment by mboczek** [comment] 2016-06-23 09:16
Ubuntu 12.04 x64 and Ubuntu 16.04 x64 - the same problem.

Any suggestions how to fix it?

**Comment by manuelmarque** [comment] 2016-06-23 09:20
Same issue here, running Fedora 23 x86_64 and running Messenger Desktop 1.4.7!

**Comment by Frantik02** [comment] 2016-06-24 04:27
Same here. Running Lubuntu 16.04 64-Bit

**Comment by granthgh** [comment] 2016-06-25 08:37
Same here. Running Mint KDE 17.3

**Comment by ForumLiker** [comment] 2016-06-25 14:15
Archlinux x64 - the same problem.
On windows10 - work's

**Comment by kasunsiyambalapitiya** [comment] 2016-06-25 14:37
Same here on Elementary OS Freya.

**Comment by quantux** [comment] 2016-06-25 16:32
Same thing here ubuntu 14.04 - 64 bits

**Comment by t3mujin** [comment] 2016-06-25 22:06
Same here, ubuntu 16.04

**Comment by MeshWeaver** [comment] 2016-06-26 01:33
Same here, Linux Mint 17.3 x64 w/ Cinnamon 2.8.8

Error message generated:
[1476:0625/213243:ERROR:browser_main_loop.cc(170)] Running without the SUID sandbox! See https://code.google.com/p/chromium/wiki/LinuxSUIDSandboxDevelopment for more information on developing with the sandbox on.
Home directory not accessible: Permission denied
[1476:0625/213243:INFO:audio_manager_pulse.cc(258)] Failed to connect to the context.  Error: Connection refused
[1476:0625/213243:WARNING:nss_ssl_util.cc(374)] Unknown SSL error -12218 (SSL_ERROR_ENCRYPTION_FAILURE) mapped to net::ERR_SSL_PROTOCOL_ERROR

**Comment by Sytten** [comment] 2016-06-26 01:49
Damn... Ok this is serious, only linux seems to be affected. My linux mint is working great, so I will provide temporary builds for you guys to test.
If you can give me feedback soon I will appreciate.

**Comment by Sytten** [comment] 2016-06-26 01:55
OK!
Please try these builds:
https://github.com/Aluxian/Facebook-Messenger-Desktop/releases/tag/v1.4.8

Try first to install them over the current software without removing manually anything.
If its not working, then locate the Messenger folders under .cache and .config (in your home folder) and remove them.

This build is working for me under Linux mint 17.3.
If you want to help me, please give as much information as you can (OS, errors, etc) and try to use the developer console to see if there are errors (its a chromium browser).

**Comment by ForumLiker** [comment] 2016-06-26 09:54
Hi Sytten, the version 1.4.8 also does not work on Archlinux x64

**Comment by mehdi-alouane** [comment] 2016-06-26 10:17
confirmed, the version 1.4.8 does work on ubuntu 14.04 x64

**Comment by Sytten** [comment] 2016-06-26 11:50
@ForumLiker your message isnt very helpful...

@mehdi-alouane great to hear that!

**Comment by i-am-cyrus** [comment] 2016-06-26 11:54
Icon now shown in the tray, but it seems that there is still the same error on Xubuntu 16.04 x64:
`[7600:0626/145025:ERROR:browser_main_loop.cc(170)] Running without the SUID sandbox! See https://code.google.com/p/chromium/wiki/LinuxSUIDSandboxDevelopment for more information on developing with the sandbox on.
ATTENTION: default value of option force_s3tc_enable overridden by environment.
[7619:0626/145028:ERROR:sandbox_linux.cc(325)] InitializeSandbox() called with multiple threads in process gpu-process
[7600:0626/145029:WARNING:nss_ssl_util.cc(374)] Unknown SSL error -12218 (SSL_ERROR_ENCRYPTION_FAILURE) mapped to net::ERR_SSL_PROTOCOL_ERROR`

![messenger_error](https://cloud.githubusercontent.com/assets/1385803/16362096/aa50ef30-3bad-11e6-8735-b67dce0f5186.png)

**Comment by Sytten** [comment] 2016-06-26 12:07
I have done some research and I think that it might be related to the fact that TLS 1.2 seems to be bugged in this version of chromium. That quite strange since the problem inst affecting everybody. 

Have you tried to delete the cache?

**Comment by Sytten** [comment] 2016-06-26 12:18
Since I already developed the version based on a more recent version of NWJS, I will propose builds based on NWJS 0.14.5 (with a more recent chromium version) tonight if I can.
My guess is that facebook decided to move to TLS 1.2 only and that created the problem.
It is strange that only the linux version seems to affected and not everybody.

**Comment by klaudiosinani** [comment] 2016-06-26 12:32
The issue seems to be also present on _**Xubuntu 16.04 32-bit**_, but i will definitely try deleting the cache and report back about the outcome! Sick work though guys! Kudos! ☺ 😁 

```
[3728:0626/150727:ERROR:browser_main_loop.cc(170)] Running without the SUID sandbox! See https://code.google.com/p/chromium/wiki/LinuxSUIDSandboxDevelopment for more information on developing with the sandbox on.
[3728:0626/150741:ERROR:backend_impl.cc(1364)] Unable to map Index file
[3728:0626/150741:WARNING:cache_util.cc(86)] Unable to delete cache folder.
[3728:0626/150742:WARNING:nss_ssl_util.cc(374)] Unknown SSL error -12218 (SSL_ERROR_ENCRYPTION_FAILURE) mapped to net::ERR_SSL_PROTOCOL_ERROR
```

![screenshot_2016-06-26_15-12-36](https://cloud.githubusercontent.com/assets/12670537/16362226/4f3464ca-3bb1-11e6-80c6-4fbb29886b1e.png)

**Comment by ForumLiker** [comment] 2016-06-26 12:52
$HOME/.config/Messenger
/opt/MessengerForDesktop
Remove, and then set a new version. did not help.

**Comment by Sytten** [comment] 2016-06-26 13:23
If you guys can give the version of libnss3 on your system that would help me! It seems to be related to that librairie as stated here: https://github.com/popcorn-official/popcorn-desktop/issues/49

The passage to nwjs 0.14.5 should also resolve the issue as stated here:
https://github.com/nwjs/nw.js/issues/4017

**Comment by i-am-cyrus** [comment] 2016-06-26 13:40
@Sytten info from
`apt-cache show libnss3`
>Architecture: amd64
Source: nss
Version: 2:3.21-1ubuntu4
Depends: libc6 (>= 2.14), libnspr4 (>= 2:4.9-2~) | libnspr4-0d (>= 4.8.6), libsqlite3-0 (>= 3.5.9), zlib1g (>= 1:1.1.4), libnss3-nssdb
Conflicts: libnss3-1d (<< 2:3.13.4-2)
Filename: pool/main/n/nss/libnss3_3.21-1ubuntu4_amd64.deb

**Comment by klaudiosinani** [comment] 2016-06-26 13:45
I am on `(2:3.21-1ubuntu4)` 

```
Package: libnss3
Priority: optional
Section: libs
Installed-Size: 3751
Maintainer: Ubuntu Developers <ubuntu-devel-discuss@lists.ubuntu.com>
Original-Maintainer: Maintainers of Mozilla-related packages <pkg-mozilla-maintainers@lists.alioth.debian.org>
Architecture: i386
Source: nss
Version: 2:3.21-1ubuntu4
Depends: libc6 (>= 2.4), libnspr4 (>= 2:4.9-2~) | libnspr4-0d (>= 4.8.6), libsqlite3-0 (>= 3.5.9), zlib1g (>= 1:1.1.4), libnss3-nssdb
Conflicts: libnss3-1d (<< 2:3.13.4-2)
Filename: pool/main/n/nss/libnss3_3.21-1ubuntu4_i386.deb
```
[Original comment](https://github.com/Aluxian/Facebook-Messenger-Desktop/issues/453#issuecomment-228599144)

**Comment by Sytten** [comment] 2016-06-26 13:50
I guess I was wrong about the libnss3 then. I'm uploading the new builds based on nwjs 0.14.5

**Comment by mcdansg** [comment] 2016-06-26 15:30
What is the default path to the cache?

Scott

**Comment by i-am-cyrus** [comment] 2016-06-26 15:55
@Sytten release 1.5.0 works for me! Console have some kind of warning:
> [2559:2559:0626/184803:ERROR:browser_main_loop.cc(271)] Gtk: IA__gtk_widget_add_accelerator: assertion 'GTK_IS_ACCEL_GROUP (accel_group)' failed

but maybe it is Ok.

**Comment by Frantik02** [comment] 2016-06-26 16:26
Finally was able to run it and log in on Lubuntu 16.04 64-Bit. Can't add the app to my Plank Dock. Probably a restart would help.

**Comment by Frantik02** [comment] 2016-06-26 16:30
Indeed, rebooting allowed the app to remain in the dock. Not sure why that, happened, though.

**Comment by Frantik02** [comment] 2016-06-26 16:32
Apparently YouTube links don't appear as messages. The person who just sent me a link appears without the https://www.youtube.com/etc... below their name.

**Comment by ForumLiker** [comment] 2016-06-26 16:48
release 1.5.0 works for me!

**Comment by granthgh** [comment] 2016-06-26 17:30
v1.5.0-beta.0 works fine on Mint KDE 17.3

**Comment by Sytten** [comment] 2016-06-26 19:58
Great to hear that!

@i-am-cyrus yes its normal

@Frantik02 not sure to understand what you mean by that? 
Notification sounds are working, wonderful! Don't know why hahaha

**Comment by Lupusaurus** [comment] 2016-06-27 14:03
v1.5.0-beta.0 works well with sound and notifications (but not the native ones). The only thing doesn't work is the right click.

![captura de pantalla de 2016-06-27 00 44 12](https://cloud.githubusercontent.com/assets/16579247/16382314/b089ee66-3c56-11e6-91fb-2a78d9eb2973.png)

**Comment by Frantik02** [comment] 2016-06-27 20:58
I now have a dock problem. If I manage to add the app to my Plank Dock (which can't be achieved via "Keep in dock", as the option does not appear when right clicking the Messenger icon), I get an icon duplicate: one to open the app and one representing the window. /:

**Comment by zapinguete** [comment] 2016-06-27 21:04
Sytten the latest v1.5.0-beta works great on Gmac OS derived from Ubuntu 14.04 64bits
Thanks a ton and blessings to you and your family.

**Comment by Sytten** [comment] 2016-06-28 00:45
Thanks to you all guys! Happy to hear its working well.

@Lupusaurus the right click where? Yes, we now have chrome-like notifications!

@Frantik02 I can't really help you with that, its really depending on your distribution and how they handle the tray icon...

**Comment by fabpin** [comment] 2016-06-28 00:55
[messengerForDesktop V:1.5.0 Beta](https://github.com/Aluxian/Facebook-Messenger-Desktop/releases/tag/v1.5.0-beta.0) Work on ubuntu 64 bits.

**Comment by Frantik02** [comment] 2016-06-28 06:48
@Sytten the thing is that before the 1.5.0 / 1.4.8 pre-releases and this whole _app.html_ issue, my Plank Dock managed the app perfectly: just one icon to launch the app and then the app window would be attached to that same window. There is something in the update that was changed and now interferes with the proper recognition of the app in the Dock. Just as a reminder, I'm running Lubuntu 16.04 64-Bit with LXDE.

**Comment by zapinguete** [comment] 2016-06-28 09:56
Frantik02 I have the same problem as you do but with Freya Elementary OS, Loki Elementary OS and Gmac OS all three of these distributions show the double ghost icon on the Dock. This very same issue occurred with Google Chrome not too long ago but was resolve within chrome's releases, at the end it had nothing to do with the distributions themselves, let us all hope that this will be the case with fbmessenger :)

**Comment by Lupusaurus** [comment] 2016-06-28 15:02
@Sytten don't remember where, but in the old releases, you are able to change the theme and check for updates by right click.

**Comment by Sytten** [comment] 2016-06-28 22:59
@zapinguete @Frantik02 
Thanks for the feedback, if it was resolved by a chrome update then it will be resolved too here when I update the framework. I'm waiting for the v0.16.0 to be stable (which should be really soon) and then I will update. This will also bring back the native notifications on demand :)

@Lupusaurus Yes I disabled it, because there was issues with the context menu appearing over the facebook menu. You can find theses setting by right-clicking the tray icon ;)

**Comment by gameslayer** [comment] 2016-07-05 14:09
Confirmed same issues on Xubuntu 16.04, will try the 1.5.0  version.

**Comment by SkebbZ** [comment] 2016-07-06 04:46
Had this issue in Ubuntu 16.04, tried the 1.5.0 beta with good results. Yesterday, however, this also happened in Windows 10. Installed the 1.5.0 beta there as well, and it worked again.

**Comment by Sytten** [comment] 2016-07-07 00:47
Good! Stay tuned for more features coming soon

**Comment by Rolice** [comment] 2016-07-18 11:34
I can confirm that `v1.5.0-beta.0` has this issue resolved under **Debian** Unstable.

**Comment by podarok** [comment] 2016-07-18 11:44
https://github.com/Aluxian/Facebook-Messenger-Desktop/releases/tag/v1.5.0-beta.0 works for 16.04 64bit Ubuntu

**Comment by Sytten** [comment] 2016-07-18 14:37
Thanks for the feedback!

**Comment by 19darion91** [comment] 2016-07-18 16:46
Version 1.5.0-beta.0 works on Ubuntu Mate 16.04. But now right-clicking in the app doesn't bring out the quick menu.

**Comment by Sytten** [comment] 2016-07-18 18:20
The settings are now only available in the context menu of the tray icon ;)

**Comment by Sytten** [comment] 2016-07-18 22:38
Beta 1 up!
https://github.com/Aluxian/Facebook-Messenger-Desktop/releases/tag/v1.5.0-beta.1

Enjoy

**Comment by 19darion91** [comment] 2016-07-18 22:52
Version 1.5.0-beta.1 works like a charm. Any chance you can make it so that the dark themes not to skin/change the visual settings for the chat bubbles so they can be affected by messenger's options for custom colours in the next beta build?

**Comment by Sytten** [comment] 2016-07-18 23:04
If you have suggestions/comments don't hesitate!

**Comment by Frantik02** [comment] 2016-07-21 05:44
Hey @Sytten , beta 1 fixed that small duplicate problem I mentioned earlier, but after installing it, the app disappeared from the _Internet_ submenu and had to add it again manually. Just letting you know. I also had to re-login btw. Thanks for the excellent work you've been doing!

**Comment by Sytten** [comment] 2016-07-21 14:26
Hum thats strange, I will verify that.
As for the relogin its normal behaviour since I delete the cache upon uninstalling and some systems do a complete removal before installing the new version...

Glad you like it :)

**Comment by CSaratakij** [comment] 2016-08-11 14:49
Confirmed -> Version 1.5.0-beta.1 fixed the problem. :+1:  
Ubuntu 16.04.1 LTS 32 bit

**Closed** 2017-02-27 14:26 UTC
Labels: beta testing, bug, investigation
