### ISSUE TITLE
Cannot add to favorites and blurry icon.

### ISSUE THREAD

**Issue by matjaz132** [Aluxian/Messenger-for-Desktop#1166] opened 2017-01-16 14:02 UTC
* Operating system: Ubuntu Gnome 16.10
* Messenger for Desktop version: 2.0.4-beta

When I pin to favorites and click to launch it creates a new blurry icon and that icon cannot be pined to favorites.

How do I fix this problem?

![screenshot from 2017-01-16 15-01-02](https://cloud.githubusercontent.com/assets/25035075/21985776/a385e1ca-dbfc-11e6-9ec5-fc1b9f04d722.png)

The left icon is added to dock by clicking on icon that launches that new icon on the right side.

**Comment by ankitch** [comment] 2017-01-18 11:44
I have the same issue on Gnome

**Comment by Frantik02** [comment] 2017-01-23 18:25
Same happens in Lubuntu 16.04 with Plank. I can't add the app to the dock as there is no "Keep in Dock" option.

**Comment by anpage** [comment] 2017-02-09 22:38
Same problem here on Fedora 25 with Gnome 3.22.2, although it doesn't look like the problem is specific to the Distro or DE.

Since there's been no response in almost a month, I'm going to take a look at fixing this.

**Comment by Aluxian** [comment] 2017-02-23 20:10
Fixed in 2.0.5, will be released soon

**Closed by Aluxian** 2017-02-23 20:10 UTC
