### ISSUE TITLE
Taskbar icon

### ISSUE THREAD

**Issue by Erramyne** [aluxian/Messenger-for-Desktop#1257] opened 2017-04-08 15:17 UTC
* Operating system: Windows 10.
* Messenger for Desktop version: 2.0.8 stable.
The tray icon is fine, the taskbar icon however isn't working. I tried reinstalling.

![screenshot_1](https://cloud.githubusercontent.com/assets/18724488/24830075/aeb40a80-1c76-11e7-9987-14e71fe13b07.png)

**Comment by Erramyne** [comment] 2017-04-08 15:34
Just an update: if I pin the icon to the taskbar using the shortcut created on the desktop during the installation it's fixed but if I launch the app without pinning it that way it gives the same result as the screenshot. So I think the icon is somehow not linked with the application itself? not sure how it all works.

**Comment by Zorakie** [comment] 2017-04-08 20:59
already mentioned here https://github.com/aluxian/Messenger-for-Desktop/issues/1206  ... it is issue persisting from older releases ...

**Comment by Zorakie** [comment] 2017-05-11 09:15
I have repaired this issue, but I cannot provide exact description as I have repaired it now and I cannot look at it again.

The problem is in links. If you install new version, even new link links to new version app, but icon link is targeted to version, that no longer exists. The problem is, that the icon is not loaded from direct link or exe, but from another link somewhere in Programs folder of user. I remember, that I have found some 2.0.7 link which were able to launch 2.0.9 app, but the icon on change alerted, that it cannot find 2.0.7 directory.

You have to replace links for app on your drive (use search toolbar for it) and than the icon on taskbar is good.


The truth is, that the current installer makes quite a mess in filesystem. Best thing will be creating classic windows installer with Program Files installation path and without versioning. Jist copy it to one folder and the app will be always in that folder, links will have same name and no problem....

**Comment by aluxian** [comment] 2017-06-11 18:05
Thanks for the detailed info. I'm going to close this as a duplicate and continue tracking this problem here: https://github.com/aluxian/Messenger-for-Desktop/issues/1206

**Closed by aluxian** 2017-06-11 18:05 UTC
