### ISSUE TITLE
Alt-space shortcut for menu activation can't be turned off.

### ISSUE THREAD

**Issue by mishurov** [aluxian/Messenger-for-Desktop#642] opened 2016-09-22 11:18 UTC
- Operating system: Gentoo
- Messenger for Desktop version: 2.0.1

I tried without success to change configs in gtk config files, by gconftool, by gsettings.

**Comment by aluxian** [comment] 2017-03-14 23:14
There's an `alt-space` shortcut? Can you provide more details? What do you want to achieve?

Closing this until there's more info.

**Closed by aluxian** 2017-03-14 23:14 UTC

**Comment by mishurov** [comment] 2017-03-14 23:24
I've already deleted my Facebook account. There was the shortcut which opened the menu, I use the right alt-space to toggle a keyboard layout. I couldn't turn the shortcut off and every time I switched a language of a keyboard, it opened the menu.

**Comment by aluxian** [comment] 2017-03-14 23:25
I see. If anyone else reports this I'll take a look. Cheers!

**Comment by edio** [comment] 2017-12-02 14:30
@aluxian may we reopen this?

`alt + space` activates menu for me. The issue is that the same shortcut is used for switching between input languages.
